// Code generated by Slice Machine. DO NOT EDIT.

import HeroSlice from './HeroSlice';
import ImageGrid from './ImageGrid';
import RelatedProduct from './RelatedProduct';

export {
	HeroSlice,
	ImageGrid,
	RelatedProduct,
};

export const components = {
	hero_slice: HeroSlice,
	image_grid: ImageGrid,
	related_product: RelatedProduct,
};
